FROM rehabstudio/python-base
MAINTAINER Peter McConnell <peter.mcconnell@rehabstudio.com>
# modified by Austin Turner <paustint@gmail.com>

# start supervisor to run our wsgi server
CMD cd /webapp/app/ && /webapp/venv/bin/python app.py

EXPOSE 5000
